searchSpaceFile: search_space.json
trialCommand: python3 ./run_finetune.py --config=./config_finetune --exp_dir=../exp --start_time=2022-06-16 --end_time=2022-06-17
trialConcurrency: 1
maxTrialNumber: 1
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
assessor:
   codeDirectory: ../code
   className: pai_assessor.PAIAssessor
   classArgs:
      optimize_mode: maximize
      start_step: 5
