experimentWorkingDirectory: ../expdir
searchSpaceFile: search_space.json
trialCommand: python3 ./run_begin.py --config=./config_begin.ini --exp_dir=../exp
trialConcurrency: 2
maxTrialNumber: 10
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
debug: true
logLevel: debug
trainingService:
  platform: local
assessor:
   codeDirectory: ../../core
   className: pai_assessor.PAIAssessor
   classArgs:
      optimize_mode: maximize
      start_step: 1
